### ISSUE TITLE
Point x and y accessors

### ISSUE THREAD

**Issue by mindrones** [d3/d3-polygon#12]
Hi,

I'm using `d3-polygon`'s functions on a large amount of nodes during a force simulation.
The problem is, a point in `d3-polygon` is an array `[x<Number>, y<Number>]` while a node in `d3-force` is `{x: <Number>, y: <Number>, ...}`, hence converting nodes to `[x, y]` slows down the simulation because of temporary arrays being garbage collected all the time.

As an example, since `polygonHull` requires `[​[x1, y1], [x2, y2], …]` I need to do `d3.polygonHull(nodes.map(node => [node.x, node.y]))`.

It would be useful to have x, y accessors to get `node.x` and `node.y` by reference and eventually avoiding the cost of duplication.

What do you think?

One approach would be to specify `x`, `y` accessors in all `d3-polygon`'s functions arguments, but I'd prefer to consume an API similar to the rest of d3:
```js
// data is an array of generic objects
d3.polygon([data])
  .x(fn)
  .y(fn)
  .vertices([data])
  .hullOf(data) // calculates the hull and stores the resulting polygon's vertices (not the input points)
  .area()
  .centroid()
  .length()
  .contains(point)
```

If it helps I'm willing to try a PR, basically imitating the [voronoi approach](https://github.com/d3/d3-voronoi/blob/master/src/voronoi.js).

Thanks!

**Comment by Fil** [comment]
I would prefer to keep the API very lightweight, unless we really can boost things a lot.

To avoid creating intermediate arrays you might extend the nodes like so:
`on("tick", () => { for (const d of nodes) d => d[0]=d.x, d[1]=d.y; })`

(Note that the hull you retrieve is then composed of the original nodes, not just [x,y] points.)
