### ISSUE TITLE
Why is Polygon.hull() result not counterclockwise ?

### ISSUE THREAD

**Issue by Kcnarf** [d3/d3-polygon#14]
The test below shows that the expected result is clockwise, not counterclockwise as mention in the documentation.

https://github.com/d3/d3-polygon/blob/1bfcdc8b63578b936c785639fa73cec566713c45/test/hull-test.js#L12

Is it due to the fact that the y-axis direction of SVGs is going down the screen, and hence inverting some common computation results ?

**Comment by mbostock** [comment]
Yes; D3 uses the default coordinate system of Canvas and SVG, which is +*x* pointing right and +*y* pointing down.

**Comment by Kcnarf** [comment]
Fine. Thanks for your clarification.

I will refactor the d3-weighted-voronoi (and subsequently d3-voronoi-map/d3-voronoi-treemap) plugin in order to fulfill this convention.

**Comment by kay-is** [comment]
Does it make any practical difference? Serious question.

I implemented the algorithm linked in the readme and it gives the same points, but goes in a different direction after the first point, still when I draw the hull, everything seems normal.

What are use-cases where the actual point ordering matters?
