### ISSUE TITLE
Add concaveHull (in addition to convexHull)

### ISSUE THREAD

**Issue by raphaelschaad** [d3/d3-polygon#21]
d3-polygon currently has d3.**polygonHull**(_points_) that returns the [convex hull](https://en.wikipedia.org/wiki/Convex_hull) of the specified points. For some applications, it would be handy to calculate the [concave hull](https://en.wikipedia.org/wiki/Concave_polygon) of a set of points.

Either, the existing method could add a second parameter _type_ (with currently supported values being _convex_ and _concave_, or, the existing method could be renamed to d3.**polygonHullConvex**(_points_) and a new method d3.**polygonHullConcave**(_points_) could be added.

**Comment by Fil** [comment]
The concave hull is not as easy to define as the convex hull and comes in many flavors (alpha-shape, etc) — a very nice and ultra fast solution is given by @mourner in https://github.com/mapbox/concaveman

**Comment by mourner** [comment]
Also see https://observablehq.com/@mourner/adaptive-concave-hull for an alternative.

**Comment by raphaelschaad** [comment]
These are great, thanks. Would it make sense for d3-polygon to implement one of these (being aware there isn't a single solution as there is for convex hull)?

**Comment by Fil** [comment]
Since the approaches we know all have heavy dependencies, I don't think it would make sense to add any of them to this lightweight module.
