### ISSUE TITLE
would it make sense to have a "polygon contains polygon" method?

### ISSUE THREAD

**Issue by nfcampos** [d3/d3-polygon#8]
ie. all the points in the 2nd polygon's array are contained in the 1st polygon

or is it so straigthforward there's no point in adding it?

**Comment by mbostock** [comment]
Hmm. I’d probably suggest implementing boolean geometry operations ([intersection ∩](http://turfjs.org/examples/turf-intersect/) and [union ∪](http://turfjs.org/examples/turf-union/)) and then use that. A polygon _A_ contains another polygon _B_ if _A_ ∪ _B_ = _A_. The [Turf library](https://turfjs.org) has implementations of these operations, ported from the [JavaScript Topology Suite](https://github.com/bjornharrtell/jsts) which is a programmatic translation of the [Java Topology Suite](https://github.com/dr-jts/jts).

**Comment by nfcampos** [comment]
thanks for the suggestion! that does appear to do what I was after. curious, why did you write d3-polygon instead of using turf, simpler api?

**Comment by mbostock** [comment]
No immediate plans to implement these topological operations, so I am closing this request.
